# create a docker-compose.yml file
version: "3"
services:
  web:
    build: .
    ports:
      - "2223:2223"
    volumes:
      - ./:/application
      - /application/node_modules

networks:
  default:
    external:
      name: timetable_maker